# Generated by Django 3.1.3 on 2020-11-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Хард скилл')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoftRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Софт скилл')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Вакансия')),
                ('teaser', models.TextField(blank=True, verbose_name='Тизер')),
                ('description', models.TextField(blank=True, verbose_name='Описание вакансии')),
                ('location_city', models.CharField(blank=True, max_length=250, verbose_name='Город')),
                ('location_country', models.CharField(blank=True, max_length=250, verbose_name='Страна')),
                ('working_conditions', models.TextField(blank=True, verbose_name='Условия работы')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Доход от:')),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Доход до:')),
                ('job_format', models.TextField(blank=True, verbose_name='Формат работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('hard_requirements', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies_requests', to='recruitment.hardrequirements', verbose_name='Хард скилы')),
                ('soft_requirements', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies_requests', to='recruitment.softrequirements', verbose_name='Софт скилы')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies_requests', to='recruitment.specialization', verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('ready_to_move', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('branch', models.TextField(blank=True)),
                ('spec', models.TextField(blank=True)),
                ('type_of_work', models.TextField(blank=True)),
                ('work_schedule', models.TextField(blank=True)),
                ('total_work_exp', models.PositiveIntegerField(blank=True, null=True)),
                ('last_employee', models.TextField(blank=True)),
                ('last_job_title', models.TextField(blank=True)),
                ('last_job_responsibilities', models.TextField(blank=True)),
                ('last_job_time', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True)),
                ('about_candidate', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('source_id', models.CharField(blank=True, max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.language')),
            ],
        ),
    ]
