# Generated by Django 3.1.3 on 2020-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
