# Generated by Django 3.1.3 on 2020-11-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
