# Generated by Django 3.1.3 on 2020-11-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_candidate_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='work_shedule',
            new_name='work_schedule',
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
