# Generated by Django 3.1.3 on 2020-11-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20201128_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.language'),
        ),
    ]
