# Generated by Django 3.1.3 on 2020-11-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20201128_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='language',
        ),
    ]
