# Generated by Django 3.1.3 on 2020-11-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20201128_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='last_job_time',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='total_work_exp',
        ),
    ]
