# Generated by Django 3.1.3 on 2020-11-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20201128_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='last_job_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_work_exp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
