# Generated by Django 3.1.3 on 2020-11-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_remove_candidate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.language'),
            preserve_default=False,
        ),
    ]
