# Generated by Django 3.1.3 on 2020-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='hardrequirements',
            options={'verbose_name': 'Хард скилл', 'verbose_name_plural': 'Хард скилы'},
        ),
        migrations.AlterModelOptions(
            name='softrequirements',
            options={'verbose_name': 'Софт скилл', 'verbose_name_plural': 'Софт скилы'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Спейиализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='vacancyrequest',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='language',
        ),
        migrations.AddField(
            model_name='candidate',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='recruitment.Language'),
        ),
        migrations.RemoveField(
            model_name='vacancyrequest',
            name='hard_requirements',
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='hard_requirements',
            field=models.ManyToManyField(blank=True, related_name='vacancies_requests', to='recruitment.HardRequirements', verbose_name='Хард скилы'),
        ),
        migrations.RemoveField(
            model_name='vacancyrequest',
            name='soft_requirements',
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='soft_requirements',
            field=models.ManyToManyField(blank=True, related_name='vacancies_requests', to='recruitment.SoftRequirements', verbose_name='Софт скилы'),
        ),
        migrations.RemoveField(
            model_name='vacancyrequest',
            name='specialization',
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='vacancies_requests', to='recruitment.Specialization', verbose_name='Специализация'),
        ),
    ]
