# Generated by Django 3.1.3 on 2020-11-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20201128_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrequest',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies_requests', to='recruitment.level'),
            preserve_default=False,
        ),
    ]
