# Generated by Django 3.1.3 on 2020-11-29 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_vacancyrequest_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг навыков')),
                ('social', models.IntegerField(blank=True, null=True, verbose_name='Социальный рейтинг')),
            ],
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['salary'], 'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterField(
            model_name='vacancyrequest',
            name='hard_requirements',
            field=models.ManyToManyField(blank=True, related_name='vacancies_requests', to='recruitment.HardRequirements', verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancyrequest',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies_requests', to='recruitment.level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='vacancyrequest',
            name='teaser',
            field=models.TextField(blank=True, verbose_name='О компании и вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancyrequest',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.rating', verbose_name='Рейтинг'),
        ),
    ]
