# Generated by Django 3.1.3 on 2020-11-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20201129_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
