# Generated by Django 3.1.3 on 2020-11-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вакансия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('employer_type', models.TextField(blank=True, verbose_name='Тип работодателя')),
                ('employer_name', models.TextField(blank=True, verbose_name='Наименование работодателя')),
                ('location_city', models.TextField(blank=True, verbose_name='Город')),
                ('location_country', models.TextField(blank=True, verbose_name='Страна')),
                ('salary_currency', models.TextField(blank=True, verbose_name='Валюта')),
                ('salary_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Доход')),
                ('salary_left_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Доход минимум')),
                ('salary_right_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Доход максимум')),
                ('job_format', models.TextField(blank=True, verbose_name='Формат работы')),
                ('candidate_level', models.TextField(blank=True, verbose_name='Уровень кандидата')),
                ('specialization', models.TextField(blank=True, verbose_name='Специализация')),
                ('branch', models.TextField(blank=True, verbose_name='Сфера применения')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='UID вакансии')),
            ],
        ),
    ]
