# Generated by Django 3.1.3 on 2020-11-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published_at'], 'verbose_name': 'вакансия', 'verbose_name_plural': 'вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Наименование работодателя'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип работодателя'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_format',
            field=models.CharField(blank=True, max_length=200, verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location_country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=200, verbose_name='Валюта'),
        ),
    ]
