# Generated by Django 3.1.3 on 2020-11-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20201125_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='branch',
            field=models.TextField(blank=True, verbose_name='Сфера применения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidate_level',
            field=models.TextField(blank=True, verbose_name='Уровень кандидата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Наименование работодателя'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип работодателя'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_format',
            field=models.CharField(blank=True, max_length=200, verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location_country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=200, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='source',
            field=models.TextField(blank=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='source_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='specialization',
            field=models.TextField(blank=True, verbose_name='Специализация'),
        ),
    ]
