# Generated by Django 3.1.3 on 2020-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20201125_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='source_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='ID вакансии'),
        ),
    ]
